name: Sync Folder

on:
  push:
    branches:
      - main
    paths:
      - 'app/queries/entities/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Checkout Repo B
        uses: actions/checkout@v2
        with:
          repository: luisinio/test_repoB
          token: ${{ secrets.REPOB_ACCESS_TOKEN }}
          path: repoB
          ref: 'main'

      - name: Create Folder
        run: mkdir -p repoB/app/queries/entities

      - name: Sync Files
        run: |
          cp -r app/queries/entities/. repoB/app/queries/entities
          cd repoB
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app/queries/entities/*
          git commit -m "Sync files from Repo A"
          git push
